- plugins-scripts/check_log.sh
- plugins-scripts/check_oracle.sh
- plugins-scripts/check_sensors.sh
I fixed some [Shellcheck](https://github.com/koalaman/shellcheck) warnings. 
It should be working everything fine, but It would be nice too if someone could take a look about the functionality.
> Shellcheck: fix most of the shellcheck warnings.

- NEWS
- README
- plugins/check_http.c
- plugins/check_mysql.c
Hi,
I found that --no-body is not working.  It just hangs and then reports a socket timeout.  This patch fixes it.
> Fix --no-body

- plugins-scripts/check_mailq.pl
Tested on FreeBSD, should be OS-independent, though.
> check_mailq: Add support for opensmtpd

- plugins-scripts/check_mailq.pl
New variable, mailq_args, is appended for postfix mta mailq commands
> Add mailq -C option for config dir or config file

- plugins/check_http.c
Pls pull.  Fixed bug #266  remove extra CR/LF after post data
> Bugfix 266

- plugins/check_http.c
Here is the fix for Bugfix_262.
> Fixed minor bug reported as Bugfix_262

- plugins/check_http.c
Fix, a small one, for bug #263  --b option not used if -S present.
> Fixes for bug #263

- configure.ac
- plugins-scripts/check_mailq.pl
Reverts nagios-plugins/nagios-plugins#290
- I needed to do this in maint.
> Revert "check_mailq: Add OpenSMTPD support"

- plugins-root/check_icmp.c
Add support to monitor jitter, MOS and Score to check_icmp
> Add support to Jitter, MOS and Score

- plugins/check_radius.c
Tested on FreeBSD. It should work on Linux too, but I have no Linux system to really test it.
However, creating portable code for mapping IP address to MAC address is very hard to do, so maybe just explicit -c option would be sufficient. On the other side, it would be a shame not to have it...
> Add calling-station-id in check_radius

- THANKS.in
- plugins-root/check_icmp.c
- plugins/netutils.c
This resolves issue https://github.com/nagios-plugins/nagios-plugins/issues/143 and https://github.com/nagios-plugins/nagios-plugins/issues/322.
> IPv6 and ICMPv6 support added to check_icmp 

- NEWS
- THANKS.in
> Changelog 2.2.2 - check_dns - pr/389

- plugins/check_http.c
- plugins/netutils.h
- plugins/sslutils.c
Work done during IETF 101 hackathon.
> TLS1.3 support based on Openssl preview.

- plugins/check_http.c
Gives a solution that addresses both #201 and #299.
Administrators with previously-configured environments will not have to change anything: using -C will still terminate immediately after the certificate is checked.
Administrators who do want both the certificate and HTTP header check in one plugin can do this by adding the --continue-after-certificate flag to their checks.
Let me know if there's anywhere that I should document the changes, other than in the helptext itself.
> check_http: Add option to continue plugin after certificate check

- plugins/check_http.c
> check_http: Typo fix

- THANKS.in
https://github.com/nagios-plugins/nagios-plugins/commit/ac6b67a1a863ca80f4026f86abd27495b76d3704
> Thanks File updated

- plugins/check_http.c
Hi 
I am new and want fix it .
#401
> fix use '-N' cause CRITICAL - Socket

- plugins/check_procs.c
not sure if that @ needs to be escaped
> adding symbol to ranges in help output

- plugins/check_snmp.c
Fixes issue https://github.com/nagios-plugins/nagios-plugins/issues/370
> Fixed --authpasswd in check_snmp help

- plugins/check_mysql_query.c
Resolves #256 
Using the test data from the forum post linked in #256, use the same command with "-a utf8" appended to produce correct output.
> Add an option to specify character set in check_mysql_query

- NEWS
- plugins/check_pgsql.c
> check_pgsql: Add an option to print the query that was run

- NEWS
- plugins/check_disk.c
- plugins/utils.c
> check_disk: add --combined-thresholds to resolve #267

- NEWS
- plugins/check_disk.c
> check_disk: fix missing timeout handler

- NEWS
- plugins/check_disk.c
> add --inode-perfdata

- plugins/check_disk.c
> check_disk: Remove extraneous output

- plugins-scripts/check_disk_smb.pl
k0ste wanted #461 re-opened, but the branch was force-pushed. We'll merge their commit in with this branch instead
> check_disk_smb.pl: added utf support & blacklisting characters instead of expanding the whitelist

- plugins/check_ntp.c
> check_ntp: add --allow-zero-stratum flag to resolve several commenters' issues on #329

- plugins/check_mrtgtraf.c
> Handle #265 without relying on RRD datastore information being populated

- plugins/check_load.c
HAVE_PROC_LOADAVG is no longer defined, see commit fe856aa957978504137c1d425815d4ed8a22be40)
> Removed dead code

- plugins/check_load.c
> Fix check_load on Mac OSX

- THANKS.in
- configure.ac
- plugins-root/pst3.c
> Resolve #446 - check_procs crash due to buffer overflow on solaris

- plugins-scripts/check_oracle.sh
https://bugzilla.redhat.com/show_bug.cgi?id=1752383
> Fix check_oracle for RHEL6

- plugins/check_http.c
Resolve #507 
Prior to this commit, check_http relied on read() returning 0 or erroring in order to
exit the loop. This commit keeps the same behavior, but once headers have been received,
it also reads the Content-Length and compares it to the number of bytes received after
the start of the body.
> Stop read()ing when Content-Length matches the amount of content received

- NEWS
- plugins-root/check_icmp.c
> Should fix #530 - 'ip' should be set even if not debugging

- NEWS
- plugins/check_http.c
See https://support.nagios.com/forum/viewtopic.php?f=35&t=57665&p=304591#p304591 for context.
> check_http: Fix issue with page length calculation

- plugins/check_smtp.c
- po/de.po
- po/fr.po
- po/nagios-plugins.pot
Implement check using TLS without STARTTLS.
It ran without any issues on our check_mk servers.
> Implement SMTP over TLS in check_smtp

- plugins/check_by_ssh.c
> Fix for issue #618 (incorrect check_by_ssh behavior)

- lib/utils_base.h
- plugins/check_procs.c
Seems like they were left over from manually applying a patch or two.
> Clean up stray '+'

- plugins-root/check_icmp.c
> check_icmp: Fix "Invalid Argument" on FreeBSD 13.1 and "setsockopt failed" for ttl

- plugins/check_mrtgtraf.c
Outgoing percentage was reported as incoming percentage.
> Update check_mrtgtraf.c Outgoing Percentage

- plugins/utils.h
Fix for : 
https://github.com/nagios-plugins/nagios-plugins/issues/582
> Fixing compilation issue : implicit declaration of function min_state

- lib/parse_ini.c
- lib/utils_base.c
- plugins-root/check_icmp.c
- plugins/check_disk.c
- plugins/check_load.c
- plugins/check_ntp_peer.c
- plugins/check_smtp.c
Fix some warnigs returned by the compiler:
stringop-truncation
uninitialized variable
> Fix some compiler warnings

- plugins-scripts/check_oracle.sh
Fix for issue 722. Improved grep to reduce false positive.
> #722: optimize grep in tnschk to reduce false positive

- plugins/t/check_ntp.t
To match current implementation in `netutils.c`.
> check_ntp.t: update the noresponse reply

- NEWS
- plugins-root/check_icmp.c
- plugins-root/t/check_icmp.t
Adds a colon to check_icmp and updates test regex
Also adds changelog line indicated that the tests were paid attention to recently
> Fix regex in test suite for updated output and keep output of plugin consistent

- plugins/check_procs.c
Some code-formatting and code style fixes to the code handling the --exclude-process option
> Some stylistic fixes to --exclude-process
