nagios-plugins.spec.in

Fixes issue preventing rpmbuild from running successfully

Correct spelling error in variable name

---

plugins-scripts/check_mailq.pl

can be catched with trival compile only run:
```
$ perl -c check_mailq.pl
syntax error at check_mailq.pl line 40, near ")
sub print_help ()"
check_mailq.pl had compilation errors.
```

fix stupid syntax error!

---

lib/extra_opts.c
plugins-root/check_icmp.c
plugins/check_dns.c

This pull request fix the Clang warning `Allocator sizeof operand mismatch`.
Command Line: 
``` sh
make 'CFLAGS=-Wall -O2 -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security'
```
Clang Version:  `clang version 3.8.0 (tags/RELEASE_380/final)`

fix: Allocator sizeof operand mismatch

---

plugins-root/check_dhcp.c
plugins-root/check_icmp.c
plugins/check_dns.c
plugins/check_hpjd.c
plugins/check_nagios.c
plugins/check_ntp.c
plugins/check_ntp_time.c
plugins/check_nwstat.c
plugins/check_real.c
plugins/check_uptime.c
plugins/netutils.c

This pull request fix almost all the Clang warnings `Dead assignment`.
Command Line: 
``` sh
make 'CFLAGS=-Wall -O2 -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security'
```
Clang Version:  `clang version 3.8.0 (tags/RELEASE_380/final)`

fix: Dead assignment

---

plugins/check_ntp.c

The delay between the first and second query was only the remainder of the current second. This is causing rate limiting issues on some server resulting in 'Offset unknown'
After this pull the delay between the first and second query is the remainder of the current second + 1.

touch ntp servers at most once every seconds

---

po/de.po
po/fr.po

I am fixing two errors and one warning at compilation time.
```
rm -f de.gmo && /usr/bin/msgfmt -c --statistics -o de.gmo de.po
de.po:1488: keyword "You" unknown
de.po:1488:12: syntax error
de.po:1489: end-of-line within string
```
and
```
de.po:9: warning: header field 'Language' missing in header
```

de,fr.po: fix syntax errors end-of-line within string.

---

plugins/check_mysql.c

this commit moves the uptime metric from metric_counter[] to metric_unit[] in check_mysql check.
This allows for the uptime performance data to be grpaphed and have an actual picture when your mysql restarts
and how many times.

Move uptime to the metric_count[]

---

plugins/check_http.c

The header that has no newline trailing it, is the last header.
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

check_http: fix parsing the last header

---

plugins/check_apt.c
plugins/t/check_apt.t

The `check_apt` plugin returns `WARNING` if there are any updates available, and `CRITICAL` if there are security updates.  While security updates are indeed important, non-critical updates are usually not considered a problem. However, there plugin does not offer a way to adjust the warning threshold.
This patch adds a switch, `--only-critical`, that makes the plugin return `OK` in case there are only non-critical updates.

Add --only-critical switch to check_apt

---

configure.ac

check_swap.c has been switched to double for dsktotal_mb,dskfree_mb
(commit 39c5e4ed595cfbda7cff566575fc5a53252f09b5)
The corresponding sscanf uses SWAP_FORMAT from configure:
ac_cv_swap_format="%*s %f %*d %f"
With doubles this now has to be:
ac_cv_swap_format="%*s %lf %*d %lf"

fix configure.ac for FreeBSD SWAPFORMAT

---

configure.ac
plugins-scripts/check_mailq.pl

Hi, I've added OpenSMTPD support to the check_mailq plugin and tested it on a Debian 9 server with OpenSMTPD v6.0.2p1. OpenSMTPD is pretty new but I am sure that others will find this feature useful. Let me know if there any changes to be done.

check_mailq: Add OpenSMTPD support

---

plugins/check_procs.c

Added --exclude-process|-X option to check_procs which takes a comma separated list to exclude from checking. This allows e.g. highly utilized mysql hosts to be checked without triggering false alarms.
Example:
[root@localhost plugins]# ./check_procs -w 20 -c 90 -m CPU
CPU WARNING: 1 warn out of 206 processes | procs=206;;;0; procs_warn=1;;;0; procs_crit=0;;;0;
[root@localhost plugins]# ./check_procs -w 20 -c 90 -m CPU -X mysqld
CPU OK: 205 processes with exclude progs ‘mysqld’ | procs=205;;;0; procs_warn=0;;;0; procs_crit=0;;;0;
[root@localhost plugins]# ./check_procs -w 20 -c 90 -m CPU -X mysqld,kswapd0
CPU OK: 204 processes with exclude progs ‘mysqld, kswapd0’ | procs=204;;;0; procs_warn=0;;;0; procs_crit=0;;;0;

Allow process to be excluded from check_procs

---

m4/ax_with_python.m4

This macro tests for a version of python greater than or equal to
2.6. To do that, it checks the python version (from within python) and
then then calls python's "print" function to output whether or not the
result is satisfactory. In python-2.x, this works fine; but in
python-3.x, the syntax of the "print" function has changed -- it now
requires parentheses. The result is that when the user has python-3.x
as his default interpreter, he sees the following error:
```
File "<string>", line 1
import sys; print sys.version[:3] >= "2.6" and "OK" or "OLD"
^
SyntaxError: invalid syntax
```
Fortunately, the parentheses also work in python-2.x, so their
addition is backwards-compatible. This commit adds the parentheses to
the version check, and allows it to work with both major versions of
python.

m4/ax_with_python.m4: don't crash on version test with python-3.x.

---

Makefile.am
nagios-plugins.spec.in
plugins-root/Makefile.am

Added install option for suid scripts without chown/chmod for packaging purposes and changed the RPM spec file to what I think the correct suid/chown/chmod settings are.
Disclaimer: I am not a developer and I may not have done this the best way possible, but it seems to work for me.

fixed? rpmbuild errors

---

lib/utils_disk.h

Fix issue "check_disk fails on large unix filesystems". 
Variable definition "double" for "dused_units, dfree_units and dtotal_units"  was insufficient to represent large free disk space ( ~8TB) and was changed to uintmax_t.
Local test was successfull:
/opt/freeware/lib/icinga/plugins/check_disk -l -e -c 5% -K 10% -p '/test'
DISK OK| /test=8482253MB;;15921817;0;16759808

Fix Issue #309

---

plugins/check_disk.c

When testing the maint branch I found that `check_disk` was getting a segfault. I ended up changing `%.0f` to `%i` to resolve the issue. I also changed some of the verbose printf statements from `%g` to `%i` to keep it consistent.

Fixed xasprintf segfault due to %f being used instead of %i

---

plugins-scripts/check_log.sh

This script returns with critical status and message "()" when the previous "diff" or "grep" fails. 
Because the case, if $count is not numeric (e.g. empty), will not be handled correctly.
This fix handle errors in "grep -c", e.g. if the file not exists, and return with Unknown status and stderr message.
Example
Log check error: grep: can't open /tmp/check_log.002330

handle errors in "grep -c"

---

NEWS
plugins/check_swap.c

PR for issue #366.
This allow handling the state in case of no swap configured/available.
By default it remains in at critical state.
See,
```
total        used        free      shared  buff/cache   available
Mem:            251          35         147           0          68         214
Swap:             0           0           0
SWAP CRITICAL - 0% free (0 MB out of 0 MB) - Swap is either disabled, not present, or of zero size. |swap=0MB;0;0;0;0
2
SWAP OK - 0% free (0 MB out of 0 MB) - Swap is either disabled, not present, or of zero size. |swap=0MB;0;0;0;0
0
SWAP WARNING - 0% free (0 MB out of 0 MB) - Swap is either disabled, not present, or of zero size. |swap=0MB;0;0;0;0
1
```
Thanks!

check_swap.c: Add --no-swap flag

---

plugins/check_dns.c

check_dns: reverse (IP to Hostname)
DNS is not case sensitive!
Old:
`./check_dns -H 192.168.178.1 -a "name = fRitZ.BoX."`
**DNS CRITICAL - expected 'name = fRitZ.BoX.' but got 'name = fritz.box.'**
New:
`./check_dns -H 192.168.178.1 -a "name = fRitZ.BoX."`
**DNS OK: 0.144 seconds response time.  192.168.178.1 returns name = fritz.box.**

check_dns: make reverse (PTR) check case insensitive

---

plugins/common.h

As of MariaDB 10.2 the headers for client no longer set the
default MySQL port. Patch fixes this for any version of MariaDB
or MySQL into the future.
See also: https://bugs.freebsd.org/223387

plugins/common.h: Set default MySQL port

---

plugins/check_http.c

A little option, which makes it possible to include the checked URL in the output. 
Normally one would use the -L option to get the output in HTML as a link - but in case one wants it in plain text, this option might come in handy.

Feature: Option to show checked url in msg output

---

configure.ac
plugins/check_load.c

Added a new parameter to show the processes that are consuming more cpu. This can be useful when receiving an email indicating that the load of a server is critical, because you can know what processes are causing it.
```
-n, --procs-to-show=NUMBER_OF_PROCS
Number of processes to show when printing the top consuming processes.
NUMBER_OF_PROCS=0 disables this feature. Default value is 0
```

Adding print top consuming processes option to check_load

---

plugins/check_http.c

This partially reverts changes applied by commit 2b38350d546ef9632ccd90e300eeaf6eda0ca32c
The mechanism brokes if there are CRs or LFs following the chunk header.
So I reverted it to the previous version.

Partial revert "fix check_http - was having constant socket timeouts"

---

plugins/check_disk.c
po/de.po
po/fr.po
po/nagios-plugins.pot

In release 2.2.1 (and earlier) check_disk doesn't support binary units (KiB, MiB, GiB, TiB). However, the SI-units are interpreted as binary units.
In this commit the following has been implemented:
1. added KiB, MiB, GiB, TiB as binary units to check_disk (plugins/check_disk.c#584-595)
2. corrected mult for kB, MB, GB, TB to decimal values (plugins/check_disk.c#573-582)
3. changed default unit from MB to MiB (plugins/check_disk.c#818,966)
4. change mult for args -k and -kilobyte (plugins/check_disk.c#603)
5. change mult for args -m and -megabyte (plugins/check_disk.c#609)
6. changed corresponding texts in language files (po/de.po#569, po/fr.po#580-581, po/nagios_plugins.pot#548)
Point 3 is changed to MiB to keep numbers identical, but unit will changes. 
Point 4 and 5 will cause …

Issue #422 - added binary units (KiB, MiB, GiB, TiB) and corrected decimal units (kB, MB, GB, TB) in check_disk

---

plugins/check_dns.c

Fixed issue with Bind 9.11.x onwards returning AAAA records using the same format as A records. The plugin now correctly detects the A or AAAA records that are returned. 
Fixed issue with Bind 9.11.x onwards performing a query for both A and AAAA records. The previous default behavior of nslookup was just A records, to ensure that exisitng users of this plugin do not get incorrect results the querytype defaults to A (if it has not already been specified). If an end user wants both A and AAAA then they need to use ANY.
This resolves issue https://github.com/nagios-plugins/nagios-plugins/issues/381.

Fixed check_dns issue with Bind 9.11.x onwards

---

plugins/check_http.c

Old and busted:
./check_http -H slashdot.org -e 666 --ssl
HTTP CRITICAL - Status line output matched "666" - 
New hotness:
./check_http -H slashdot.org -e 666 --ssl
HTTP CRITICAL - Invalid HTTP response received from host on port 443: HTTP/1.1 200 OK

fix error message when -e <response> fails

---

plugins-scripts/check_oracle.sh

PMON process of oracle 18c XE is neither prefixed by asm_ nor by ora_ but by xe_

check_oracle: Added support for Oracle 18c XE for --db

---

NEWS
plugins/check_smtp.c

This enables checks of SMTP servers that expect the haproxy
PROXY protocol:  -o smtpd_upstream_proxy_protocol=haproxy.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

check_smtp: Add option to prefix PROXY header

---

plugins/check_radius.c

When constructing a calling-station-ID, check_radius traverses a list of local network interfaces. Due to insufficent pointer checking, this can result in a segfault due to null pointer dereference when certain types of interfaces are configured on the system (I triggered this behaviour on a tun interface). As they don't carry the information needed to construct the ID, we can safely skip them when traversing the list.

Fix null pointer dereference in check_radius

---

plugins/sslutils.c

Apache supports PHA with TLS1.3

Enabling Post Handshake Authentication for Nagios-plugins

---

NEWS
plugins-scripts/check_file_age.pl

Fixes #382 and a couple of other issues:
- Previously, the plugin would exit at the first file not found. This PR has the plugin continue ("`next;`") instead.
- Previously, the plugin would use the last result rather than the 'worst' result. This PR tracks the highest return level and uses that for plugin output.

[FR] Make check_file_age.pl use multiline plugin output

---

NEWS
plugins/check_snmp.c

--strict causes expected OIDs (the arguments to -o) to be compared to the actual OIDs (retrieved by the call to snmpget). 
It also means that the MIBs list (specified by -m) will never be set to `ALL` unless done explicitly by the user

check_snmp: add --strict flag

---

plugins/check_ups.c

`check_apcaccess` plugin for APC UPSes is able to report battery runtime left, e.g.:
`UPS OK - SMART-UPS 1000 Status=ONLINE Utility=223.6V Batt=100.0% Load=14.0% Temp=39.6°C Left=71.0min`
This adds similar functionality to the `check_ups` plugin. The runtime left is included in the status string:
`UPS OK - Status=Online Utility=236.1V Batt=100.0% Load=21.0% Temp=25.0C Left=74.0min`
as well as in the performance data.

check_ups: battery runtime left check

---

NEWS
plugins/check_ntp.c
plugins/check_ntp_time.c

I wasn't able to cherry-pick the commits from https://github.com/monitoring-plugins/monitoring-plugins/pull/1605, but these changes are equivalent to that PR for this project.
(Fixes issues related to #329)

Add option to delay check_ntp, check_ntp_time between packets (default 2s)

---

.gitignore
configure.ac
plugins-scripts/Makefile.am
plugins-scripts/check_ssl_validity.pl

Previously, users that wanted to check the status of their SSL certificates would need to use check_http, which doubles as a general web plugin and has become somewhat complicated to use. This PR adds a new plugin which only handles the certificate portion of that plugin, which will (potentially) allow us to refactor check_http later.
Adds the plugin offered in #72, with some changes:
- doexit() prints the status of the plugin before finishing
- Certificates' altnames (dNSNames) are treated as globbing patterns
- User can opt to use OCSP over CRL checking via --ocsp (#273). If the OCSP responder needs to be given a specific hostname, this can be specified by --ocsp-host.

Add a plugin specifically for certificate checking

---

plugins-root/check_icmp.c

check_icmp: resolve #404 by fixing hosts_ok calculation

---

plugins/check_ntp.c
plugins/check_ntp_peer.c
plugins/check_ntp_time.c

check_ntp and friends: change calls to perfdata() to preserve complete threshold in output

---

plugins-root/check_icmp.c

check_icmp: Resolve #451 by moving call to bind() after call to socket()

---

plugins/check_dns.c

Logic is incorrect when processing an error code returned by nslookup. The following code bails out early _and_ overwrites the error message for errors such as an invalid domain:
```
int tmp = error_scan(chld_out.line[i]);
result = (result == STATE_UNKNOWN)
? tmp
: (result < tmp)
? tmp : result;
if (result != STATE_OK) {
msg = strchr (chld_out.line[i], ':');
if(msg) {
msg++;
}
else {
msg = chld_out.line[i];
}
break;
}
```
Examples:
```
~/tmp/nagios-plugins-2.0.3/plugins$ ./check_dns -H no-such-domain.com
Domain no-such-domain.com was not found by the server
~/tmp/nagios-plugins-2.2.1/plugins$ ./check_dns -H no-such-domain.com
DNS WARNING -           192.168.1.1
~/tmp/nagios-plugins/plugins$ ./check_dns -H no-such-domain.com
Domain no-such-domain.com was not found by the server
```

Fix incorrect error message when nslookup returns an error status

---

plugins/check_ping.c

Due to an extra `printf()` the output from the plugin is incorrect when ping output cannot be parsed:
Before fix:
```
$ check_ping -w '600.0,30%' -c '1200.0,60%' -p 5 -t 20 -H somedomain.com
/bin/ping -n -U -W 15 -c 5 somedomain.com
CRITICAL - Could not interpret output from ping command
```
After fix:
```
$ check_ping -w '600.0,30%' -c '1200.0,60%' -p 5 -t 20 -H somedomain.com
CRITICAL - Could not interpret output from ping command
```

Remove redundant debug print from check_ping

---

plugins/check_http.c

If a port is specified this fails. The host_name needs to be updated since the socket/connect calls require an IP/DNS string with the port specified separately to be valid.

Update host_name if port specified.

---

plugins/check_dns.c

Currently `check_dns` returns somewhat unhelpful error messages for some Connection timed out and Connection refused errors returned by nslookup. 
Examples on Ubuntu 18.04:
```
$ nslookup foo.com 1.2.3.4
;; connection timed out; no servers could be reached
$ ./check_dns -H foo.com -s 1.2.3.4
DNS WARNING - nslookup returned an error status
$ ./check_dns -H foo.com -s 1.2.3.4
Connection to DNS 1.2.3.4 timed out
```
```
$ nslookup -type=ANY foo.com ns1.dynadot.com
;; Connection to 35.160.240.86#53(35.160.240.86) for foo.com failed: connection refused.
;; Connection to 54.69.45.191#53(54.69.45.191) for foo.com failed: connection refused.
;; Connection to 52.25.56.204#53(52.25.56.204) for foo.com failed: connection refused.
;; Connection to 54.68.4.223#53(54.68.4.223) for foo.com failed: …
```

check_dns: Improved error messaging for "connection timed out" and "connection refused" cases.

---

configure.ac

Revert commit b7ee01a257d0bee30b3ef4d579ad56533f389e70 (Fix for issue #139) which incorrectly modifies timeout behaviour of the `check_ping` plugin.
See also:
https://github.com/nagios-plugins/nagios-plugins/issues/419
https://github.com/nagios-plugins/nagios-plugins/issues/323
https://github.com/nagios-plugins/nagios-plugins/issues/139
The above commit modified the `/bin/ping` command line to use the `-W` parameter instead of `-w` for specifying the timeout. `-w` is a global timeout for the command whereas `-W` specifies the maximum time to wait for a single ping response. This caused a number of issues:
1. For unresponsive hosts instead of the ping command timing out and providing useful output, viz:
`PING CRITICAL - Packet loss = 100%|rta=1200.000000ms;600.000000`
we get instead: …

Fix inconsistent timeout behaviour of check_ping plugin

---

configure.ac

Hello,
I'm no perl expert, but the check always fails on my Ubuntu 18.04 installation. With the whitespace removed it works and looking at the other parameters it seems to be correct.
Regards,
Ben

Fix typo in check for required perl modules for check_ssl_validity

---

plugins/check_snmp.c

I have a PDU that reports amperage in 1/100ths of an AMP. Using this new `--multiplier` feature you can convert numeric values before doing comparisons.
**Before:**
SNMP OK - amps 600 | amps=600;1110;1200 
**After with `--multiplier 0.01`**:
SNMP OK - amps 6 | amps=6;11;12

Add an option to multiply check_snmp results by a given factor

---

plugins/check_http.c

Added option -o/--output-body-as-perfdata to append the http response body
to the output line. This will only happen for responses that are of state "OK".
Imagine the requested webserver responds with 200 OK and the text:
|'first variable'=42|'second variable'=111
This text will be appended to the plugin output, and is treated as regular
performance data.
The switch -o or --output-body-as-perfdata enables this feature.

Add option to output response body as performance data

---

plugins-scripts/check_log.sh

Current manpage for check_log clips the usage info off. I've added linebreaks around col 95 to be more consistent with other script plugins, and to fix the manpage looking weird.
https://nagios-plugins.org/doc/man/check_log.html

modify check_log.sh with line breaks so manpage looks nice

---

plugins-scripts/check_ifstatus.pl

Hello,
My colleague Eloi did add a -d switch to check_ifstatus.pl in order to be able to exclude interfaces on a per description basis. This allows to exclude interfaces that have a pattern such as "phone" in their descriptions.
Could you check this PR?
Thanks.
Best regards,

Add -d switch to check_ifstatus.pl

---

plugins/check_ntp_time.c

They are referred to in the list of long options, work fine once allowed,
but were not actually allowed.

check_ntp_time: Add -C and -W to allowed list of short options

---

plugins-scripts/check_log.sh

On recent RHEL7 variants with multi-mb logs that continue to be written to, the diff command never exits and uses 100% CPU causing this log check to fail.
Copying the logfile to a temporary file (using the same logic used later in the script) seems to solve this issue for the most part. I believe this would resolve the issues, and not create any extra issues.

use a temp file for log diffing

---

plugins/check_smtp.c

This pull request adds a break; to stop case 'D': Check SSL cert validity from falling through to case 's': ssl

Fixes #648 Unable to check certificate with starttls in check_smtp

---

plugins/check_smtp.c

This change moves the certificate check out of the block that initializes STARTTLS.  This should fix #651, but is based on work for #648 and #649.

check_smtp: Permit certificate check with both --ssl and --starttls

---

plugins/check_dig.c

produce false "OK" status reports, such as when the -a string is
10.4.5.2 and the DNS result is 210.4.5.247.
Fixes #641

check_dig.c: Fix string matching of -a parameter so that partial matches will not

---

plugins-scripts/check_mailq.pl

`$?` is only set *after* `close()` has been called.
This fixes the issue where Postfix' `mailq` can't read the queue and returns garbage which can't be parsed by the later code.
Fixes #663

Fix #663 - close MAILQ before analyzing the return code

---

plugins-scripts/check_log.sh

On recent Linux systems, it is possible to grant the nrpe daemon additional capabilities, such as `CAP_DAC_READ_SEARCH` (bypass file read permission checks and directory read and execute permission checks), even though the nrpe daemon typically does not run as root.
But by design, when a non-root process calls `access(2)` or similar permission checks, the kernel answers using an empty set of capabilities. Quoting the access(2) man page verbatim:
> This allows set-user-ID programs and capability-endowed programs to easily determine the invoking user’s authority. In other words, access() does not answer the “can I read/write/execute this file?” question. It answers a slightly different question: “(assuming I’m a setuid binary) can the user who invoked me read/write/execute this file?”, …

don't use "[ -r FILE ]" to check for readability in check_log

---

plugins/check_tcp.c

for the sake of readability and compatibility with monitoring-plugins/monitoring-plugins#1614 .
The latter matters for Icinga/icinga2#8208 .

check_tcp: add --sni as alias for -N

---

NEWS

The release date of 2.4.3 is wrong... I fixed the correct year

Fix NEWS release date

---

configure.ac

This solves the following error for VPATH builds:
```
/opt/src/nagios-plugins-2.4.4/configure: line 14326: release: No such file or directory
```

configure needs full path to release file

---

plugins-scripts/check_sensors.sh

As of Fedora 38, egrep now complains of being obsolescent and exits 2, causing use of the plugin to fail. Since the script does not use egrep's extended features, why not call just "grep" instead?

Use ordinary grep in check_sensors

---

plugins-scripts/check_mailq.pl

With check_mailq.pl invoked when SSMTP is installed but '-M postfix' is used, 'mailq: Mail queue is empty' goes to stderr, which is not captured. Redirecting stderr to stdout fixes the issue.

Handle "mailq: Mail queue is empty" for SSMTP

---

plugins-scripts/check_log.sh

The check_log script will create a folder in the `/tmp` directory called something like `temp_check_log.BhlvxjsLE9` that if done enough times on sufficiently large log files would fill the entire disk space. This ensures that this script removes the temporary files it creates.
Also I get rid of an echo that isn't necessary.

Fix error with check log filling up tmp directory

---

NEWS
plugins/check_snmp.c

The only difference between the correct UNKNOWN output when threshold parameters are given vs not, is - when given threshold params - the response passes the if statement:
`if (thlds[i]->warning || thlds[i]->critical || calculate_rate || is_ticks || offset != 0.0 || multiplier != 1.0) {`
which is immediately after that else. It then promptly fails what used to be a check for any of (-0123456789) - replaced by my check for parens - and dies. That's why the error is caught when thresholds are given and not when they aren't. My impression is that if it's chill to die in this if statement then it's chill to die directly before given the same circumstances (namely when the response is an error message). I just put a whitespace check in the else and a subsequent die() if it fails.

Fix #679 by adding whitespace check

---

NEWS
plugins/check_snmp.c

Testing Plan:
- Tested plugin using this command: `/usr/local/nagios/libexec/check_snmp -H 192.168.223.19 -C public -P 2c -o ipv6IpForwarding.0  -v -v -v -v -w 2 -c 6`
- Before making the changes, this command returns:
```
/usr/bin/snmpget -Le -t 3 -r 5 -m ALL -v 2c [context] [authpriv] 192.168.223.19:161 ipv6IpForwarding.0
IP-MIB::ipv6IpForwarding.0 = INTEGER: notForward1000ing(2)
Processing oid 1 (line 1)
oidname: IP-MIB::ipv6IpForwarding.0
response: INTEGER: notForward1000ing(2)
SNMP CRITICAL - 1000 | IP-MIB::ipv6IpForwarding.0=1000;2;6
```
- Notice that the response uses the value 1000 which is in the OID name rather than the actual OID value (which is 2).
- After making the changes, this command returns:
```
/usr/bin/snmpget -Le -t 3 -r 5 -m ALL -v 2c [context] [authpriv] …
```

Fixes #720 - check_snmp numeric OID name bug

---

NEWS
plugins/check_snmp.c

- This fix maintains the fix to issue #720 while hopefully addressing the subsequent problems noted in issue #743. 
- With this change, the integer return value from snmpget is only accessed via searching for open parentheses if said character exists, otherwise it parses as before - by checking for the first instance of "-0123456789". 
- NOTE: There are still potentially edge cases (namely a return value with an oidname that both has no parentheses and has integers in the name - but I truly hope that isn't possible). 
- I do not have the equipment required to test specific MIBs but this change largely reverts my previous change so particularly extensive testing is not necessary for such MIBs that no longer worked with the change made in 2.4.7.
- For those who encountered issues with 2.4.7 …

Potential robust fix for check_snmp issues

---

plugins/t/check_dns.t

One more test was added more than [8 years ago](https://github.com/nagios-plugins/nagios-plugins/commit/309e68f75c1c9f5519770ba78131793c52ef2edb) but number of expected tests was not changed.

Fix number of tests for check_dns.t

---

plugins/t/check_fping.t

When `check_fping` tries unresolvable address it returns 3, not either 1 or 2 as expected by the `check_fping.t` test:
```
$ plugins/check_fping 8.8.8.8 ; echo $?
FPING OK - 8.8.8.8 (loss=0%, rta=4.700000 ms)|loss=0%;;;0;100 rta=0.004700s;;;0.000000
0
$ plugins/check_fping 10.0.0.1 ; echo $?
FPING CRITICAL - 10.0.0.1 (loss=100% )|loss=100%;;;0;100
2
$ plugins/check_fping do-no-exist ; echo $?
FPING UNKNOWN - IP address not found
3
$
```

check_fping.t: unresolvable address returns unknown status

---

plugins/t/check_load.t

The `check_load` plugin output was [changed](https://github.com/nagios-plugins/nagios-plugins/commit/1e8db3deaa83dc7beca78d6382c435de37e835e3) several years ago, but related test was not updated.

check_load.t: consider new per CPU format

---

plugins/t/check_ssh.t

The timeout message no longer contains `after X seconds` since Oct 2015 (see `netutils.c`).

check_ssh.t: update timeout message

---

plugins/t/negate.t

This fixes two issues in the `negate.t` test:
1. the `negate` check no longer returns `No data returned from command` since Oct 2020.
2. the timeout message no longer contains `after X seconds` since Oct 2015 (see `netutils.c`).

negate.t: fix tests

---

plugins/t/check_disk.t

There are two issues with current `check_disk.t` test:
1. free space percentage is printed with two decimal places,
2. the default unit is `MiB`, not `MB`.

Fix tests for check_disk

---

plugins/t/check_by_ssh.t

The `check_by_ssh` never exits with [exitcode > 3](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_by_ssh.c#L122) when there is nothing on stderr, but `check_by_ssh.t` assumes it does.  Such assumption is wrong.

check_by_ssh usually does not return out of bounds exitcode

---

plugins/tests/check_procs.t

This fixes two issues in the `check_procs.t` test:
1. If there is no user with uid -2 then the test would fail.  Similar issue with uid 501 was fixed back in 2014.
2. The `check_procs` plugin output contains performance data since Aug 2019 but this test was not updated accordingly.

tests/check_procs.t: skip tests for uid -2 if it does not exist and add perf data

---

plugins/tests/check_procs.t

Per the --help output of check_procs
```
--ereg-argument-array=STRING
Only scan for processes with args that contain the regex STRING.
```
This argument specifically runs the regex against the _arguments_ of a process, but the test assumed this meant it was running the regex against the entire string.

Fix incorrect check_proc test

---

plugins/tests/check_http.t

Such alarms cannot work since `NPTest->testCmd` contains its own alarms (since Sep 2013).

tests/check_http.t: do not use alarm() to timeout tests

---

plugins-scripts/t/check_file_age.t

Pretty simple, plugin has two spaces at the end of output. Need to make sure regex matches this

Add spaces to regex of check_file_age.t

---

plugins/check_swap.c

This PR allows to run `check_swap` without thresholds, which can be used for a purely informational run, e.g. for retrieving statistics. 
```
$ ./plugins/check_swap
SWAP OK - 100% free (4091 MB out of 4091 MB) |swap=4091MB;0;0;0;4091
$ ./plugins/check_swap 
SWAP OK - 0% free (0 MB out of 7627 MB) |swap=0MB;0;0;0;7627
```
Without thresholds, the plugin always returns an OK status. This was added under 'Notes' within the `--help` output:
```
Without thresholds, the plugin shows free swap space and performance data, but always returns OK.
```
With thresholds defined, the plugin does the known behaviour:
```
$ ./plugins/check_swap -w 10% -c 5%
SWAP CRITICAL - 0% free (0 MB out of 7627 MB) |swap=0MB;762;381;0;7627
```
This PR does not break existing configurations because prior to the PR, …

Allow check_swap to run without thresholds

---

NEWS
plugins/check_dig.c

- There was an [issue](https://github.com/nagios-plugins/nagios-plugins/commit/cbdfd8a9bd83ed22dc6e9b3e5104ed81de388596) reported with the check_dig plugin where it returned OK on records that only partially matched the expected address. 
- The fix was to exact match records.
- This fix was not backwards-compatible and broke (at least) calls to check_dig that matched TXT records. This specific issue occurs  because DNS TXT records are quote-wrapped and the expected address is not. 
- To maintain backwards-compatibility, my changes alter the exact match change, making it only occur when an additional argument is provided. If this argument is not provided, the method used prior to the last commit is used (partial match).
- ./check_dig  --hostname=8.8.8.8 --query_address=example.org …

check_dig Exact Match

---

plugins/check_snmp.c

The recent changes (post 2.4.6) to `check_snmp` mean that attempting to do string matching on OIDs that return an IP address value will fail as they will traverse the "error path" despite there not actually being an error.
This fixes that though it does also change the behaviour by removing the `IpAddress: ` prefix from the string being matched which is in line with how other responses are handled.

Handle snmp IpAddress responses

---

plugins-root/check_icmp.c

A setuid() return value is not checked in nagio's check_icmp plugin:
https://github.com/nagios-plugins/nagios-plugins/blob/ee69a7d8aeaef375bbe5680deebbf59ce4455a68/plugins-root/check_icmp.c#L726C1-L729C1
man 2 setuid() states the following:
> RETURN VALUE
>       On success, zero is returned.  On error, -1 is returned, and errno is set to indicate the error.
>
>       Note: there are cases where setuid() can fail even when the caller is UID 0; it is a grave security error to omit checking for a failure return from setuid().
In the unlikely event where setuid() fails, privileges of the plugin would not be dropped and commands would be run as root. This would lead to privilege escalation.
The attached patch fixes this by aborting execution when such an event occurs.

check_icmp: Uncheck return values of set*id() family functions

---

configure.ac

The `egrep` alias for `grep -E` is deprecated:
```
$ egrep
egrep: warning: egrep is obsolescent; using /bin/grep -E
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
```
The alternative `grep -E` is part of POSIX and should be even more reliable. This commit finds & replaces them all in `configure.ac`.

configure.ac: update egrep -> grep -E
